### PR TITLE
fix in bleach linkifiy

### PR DESCRIPTION
**Pull request by Natay**
- removed repeated call to bleach linkify and added nofollow callback into list of callbacks with embedder.

### CODE REVIEW

**Comment by ialbert** [comment]
does this really fix things?

one thing I know, messing with the linkify is tricky business

**Comment by ialbert** [comment]
there are reasons (alas often undocumented) why it usually gets called in so awkward ways

**Comment by Natay** [comment]
We check if the object start with http/https/ftp in the embedder but do not when using linkify the second time with the nofollow callback, which is when extensions are turned into links. 

We can add the nofollow callback to the list when initially calling linkify to avoid calling linkify twice, we can also have a third callback function ( validate_links) that gets added to both calls and checks if the object start with http/https/ftp .

Testing it out with this method, both nofollow and embedding callbacks work and links are correctly validated.

**Comment by ialbert** [comment]
great! excellent!

**Pull request merged**
