### PR TITLE
Deploy To Heroku Button 

### PR DESCRIPTION
**Pull request by Lohit13**
Deploy to Heroku button in the README.

### CODE REVIEW

**Comment by Lohit13** [comment]
@ialbert 
Deploy to Heroku button for biostar3.0 is done as well. Only issue is the redirection to lvh.me:8080

**Comment by brainstorm** [comment]
@Lohit13 can you describe:

1) Which issues are you experiencing.
2) What did you try so far to fix it.
3) How attempts to fix it in point 2 failed?

Please have a look at this great paper:

http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002202

**Comment by ialbert** [comment]
Also the site does not redirect to  lvh.me:8080 at all times, only if this was set as its host domain. One has to set the correct site domain in the settings.

See for example that this site works fine:

http://test.biostars.org/

**Comment by Lohit13** [comment]
Hey,

I tested using the correct domain name in the settings. However, I'm getting a 301 error (ie- redirection). I guess it's something to do with a trailing slash (from what I'v read on the net). 

Could you please see if these settings are okay? https://github.com/Lohit13/biostar-central/blob/3.0/run/heroku.py

or could you please give me the settings file used in http://test.biostars.org/.

**Comment by Lohit13** [comment]
Hey, 

@ialbert 
I'm wrapping up the gsoc tasks. I'm deploying a Biostars 3 instance for Neurostars. However, I'm encountering the same lvh.me hostname problem. There does not seem to have much documentation on it. Could you please forward your custom .env and .py files for http://test.biostars.org/ when it was configured. I'll use it as reference to fix the issue.

Thanks and Regards
Lohit

**Comment by ialbert** [comment]
When you initialize the site it must be initialized with the correct domain
like so:

These values need to be overriden to the correct ones (line 32 to 44):

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/settings/values.py#L32

when the site is migrated it triggers setting these values(you should not
need to do anything here it is just for reference):

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/settings/values.py#L32

**Comment by ialbert** [comment]
we moved to new codebase.

**Pull request closed without merging**
