### PR TITLE
added phpbb import script

### PR DESCRIPTION
**Pull request by Lohit13**
the biostar 3 version of the sql import script

### CODE REVIEW

**Comment by brainstorm** [comment]
@Lohit13, I would suggest a better name for this import script... since it's a bit phpBB specific, I would go for `import_phpbb`, what do you think? Naming things in programming is tricky, but worth giving it some time so that other people can easily understand:

http://www.slideshare.net/pirhilton/how-to-name-things-the-hardest-problem-in-programming

Another issue comes when running your script in a "clean" environment. This is a very common deployment issue:

```
$ python manage.py import_sql
/Users/romanvg/dev/biostar-central/biostar3/forum/management/commands/import_sql.py:85: SyntaxWarning: import * only allowed at module level
  def import_posts(host, user, password):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/romanvg/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/romanvg/dev/biostar-central/biostar3/forum/management/commands/import_sql.py", line 4, in <module>
    import MySQLdb as mdb
ImportError: No module named MySQLdb
```

Which is easily solved adding the offending module in `init/pip/base.txt`, for instace. But before that, are you able to refactor your script so that it doesn't use additional external modules? Or even better, any temporary MySQL data import at all? That would be fantastic!

Hope that helps!

**Comment by Lohit13** [comment]
@brainstorm indeed. phpbb would import_phpbb is a better suited name for it. I'll change it. 
Thanks for sharing the resource!

A script which doesn't use any external module is possible. However, it'll be very specific to the php_bb db backup. I'll write the script and get back to you by tomorrow.

**Comment by Lohit13** [comment]
I have removed the MySQLdb dependency. The script now parses the sql file itself and extracts the posts from it. Consequently, only -f option is needed in the command now

**Comment by ialbert** [comment]
it is a good start but this needs to be made a lot more robust and
universal all across.

First it needs a documentation on how to produce the database dump, what
the dump will look like and what the tool does.

Then it needs to dump both author table and post table. First it needs to
load up the authors and create a new user for all emails that are not
already in the database. That way proper authorship to the post is
maintained. Then using these authors it can parse the data for posts and
insert those with the correct authorship information.

Finally I don't like the manual parsing of SQL statements - it feels to
brittle and hard to maintain. It would be much better to export the MySQL
database into a CSV file with headers then parse that.  This will allow to
write data exporters for any other content management system.

It just needs a simple spec for the the two CSV files for the he authors,
posts and the system can then parse that.

On 26 May 2015 at 19:20, Lohit Parmar <notifications@github.com> wrote:

> I have removed the MySQLdb dependency. The script now parses the sql file
> itself and extracts the posts from it. Consequently, only -f option is
> needed in the command now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ialbert/biostar-central/pull/351#issuecomment-105695678>
> .
>



-- 
Istvan Albert
Associate Professor, Bioinformatics
Pennsylvania State University
http://www.personal.psu.edu/iua1/

**Comment by Lohit13** [comment]
Hey,

The database dump comes for the NIF community. They give it in .sql format. I wrote the script according to the file given to me.

Regarding the users, yes, the new users should be made. However, the db dump I have does not contain post user information. So I used the admin user (as logically the admin would be the one importing). 

I agree, parsing the sql file in python is not foolproof as splitting the rows to extract the title and body might throw an exception as those fields might contain the delimiter as well. Hence, I used MySQL in the first previous script I wrote. 

CSV is a much easier way to handle such data, but NIF did not provide the dump in any other format. So in my opinion, if it the sql file has to be used, using the previous script is much better. 

@brainstorm @ialbert Kindly advise on how to proceed

**Comment by Lohit13** [comment]
Hey,

I'v changed the script to use csv files.

However, the user issue remains as they have an empty 'username' field (no email or name field), so I'v used the admin user.

**Comment by ialbert** [comment]
the user data is there in another table, it has foreign keys to the user
table.

Your script need to read the users first, populate the users then read the
posts.

Also it is important that posts that are in a thread follow the Biostar
format, first post is the "question" responses to the top post are answers
and the the other become comments.

**Comment by Lohit13** [comment]
Edited the script. It now looks for an existing user. If not found, it creates one.

Change in the execution of script:
python manage.py import_phpbb -p /path/to/posts/table.csv -u /path/to/users/table.csv

**Comment by brainstorm** [comment]
Hello @Lohit13,

I just tried to run the script this way:

```
romanvg$ python manage.py import_phpbb -p nif_forums.csv/nif_forums_temp.phpbb_forums.csv -u nif_forums.csv/nif_forums_temp.phpbb_users.csv
```

And it did import the 9 posts present in the CSV file. Unfortunately, it seems that the questions are created empty, without content. I looks like this on my machine:

skarmavbild 2015-06-03 kl 17 49 11

Am I doing something wrong?

**Comment by Lohit13** [comment]
The script uses the 'posts' and 'users' table. 

so -p should be supplied with phpbb_posts instead of phpbb_forums

**Comment by brainstorm** [comment]
Aha! Gotcha, good stuff, now it worked:

image

Although it seems that the text in there needs some filtering/formatting (do you see the \n's?), could you please fix that? Also, details like the `url:` shown below could be filtered via simple python `.replace`patterns so that they look like clean URL links:

image

Good job!

**Comment by Lohit13** [comment]
sure, i'll filter the text and update the pr

**Comment by brainstorm** [comment]
Documentation-wise, could you ask how NIF exported those files from their MySQL database (OUTFILE statement) and put the following example in the header of your script?:

```
python manage.py import_phpbb -p nif_forums_temp.phpbb_posts.csv -u nif_forums_temp.phpbb_users.csv
```

That way, new people can quickly get a grasp on how to export from their old phpBB instances and get rolling fast with BioStars :)

**Comment by Lohit13** [comment]
filtered body content. just waiting for the NIF guys to provide OUTFILE statement.

**Comment by brainstorm** [comment]
@Lohit13, seems like the last changes broke the build?:

https://travis-ci.org/ialbert/biostar-central/jobs/65311464

Please fix it ;)

**Comment by ialbert** [comment]
hmm, I have to look at this, I think the commit did not touch any file that
is tested.

occasionally tests fail because the random way objects are created and
those are bugs - and sometimes the remote infrastructure does something
odd.

**Comment by Lohit13** [comment]
looks like Prof. Albert is right. It was a random error. 

Updated the -h option to display the usage and added the docs

**Comment by Lohit13** [comment]
minor update. Post Date also imported now

**Comment by Lohit13** [comment]
@ialbert 
Hey,
Hope your arm is healing well!

Do you require any other changes in these two PRs? If no, I can update it with the Deploy To Heroku button.

Regards
Lohit

**Pull request merged**
